### ISSUE TITLE
ADR on daily Email limits

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1160]
## Description
As a Notify developer,
I need to document how the daily email limit per service will work and apply,
So that I can answer the how and what on the daily email limit epic.

WHY
To document and explore our options around daily email limit and have consistency with daily SMS limit and Notify's throughput limitations.

WHAT
An architectural decision record.

VALUE
Explore, communicate, review and document.

Acceptance Criteria** (Definition of done)
 - [ ] ADR is written, peer reviewed and approved.
 - [ ] A few questions are answered 

*These questions:
What will the daily email limit be by default per service?
How can we honour legacy services that have already been sending higher volumes of emails daily?
How can we bake in security so low volume services don't have higher daily limits than they need, creating a vector for risk?
How can we surface the daily email limits to the user?
How can we keep track of daily email limit per service?

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1160?planning-poker) with Zenhub @andrewleith @jzbahrai @smcmurtry @whabanks

**Comment by yaelberger-commits** [comment]
I used another ADR card as a template, but please refine the questions we need to answer with this ADR

**Comment by yaelberger-commits** [comment]
@andrewleith @jzbahrai @smcmurtry please get your estimates in for this one

**Comment by smcmurtry** [comment]
Do we need an ADR for this? I thought we were just doing the same thing that we did for the SMS limit?

**Comment by yaelberger-commits** [comment]
@smcmurtry the ADR would help us answer what the default daily email limit should be per service, since it will be much higher than for SMS. 
I think the ADR will follow the same format as the one for SMS, but I imagine some things might be different for email or unique to email limits than SMS, but maybe I'm wrong.

**Comment by smcmurtry** [comment]
@yaelberger-commits Okay that makes sense to inform us how much we can raise the email limit in the future. But I don't think this should block the work to implement a separate email limit and get rid of our old "combined" limit. We could initially set the email limit to be the same as whatever the current "combined" limit is for a service, and then we would have essentially the same limits as today since most services have a small SMS limit.

**Comment by smcmurtry** [comment]
@yaelberger-commits Okay that makes sense to inform us how much we can raise the email limit in the future. But I don't think this should block the work to implement a separate email limit and get rid of our old "combined" limit. We could initially set the email limit to be the same as whatever the current "combined" limit is for a service, and then we would have essentially the same limits as today since most services have a small SMS limit.

**Comment by yaelberger-commits** [comment]
@smcmurtry I agree! We can implement the limit with the default being 10,000, and then measure and decide if that's good or we need to change it through the ADR later. 
But we do need to make sure we honour services current limits that are higher than 10,000 a day
