### ISSUE TITLE
Write content about security issue for forced password reset on "System Status" page

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1187]
## Write content about security issue for forced password reset on "System Status" page

As a Notify user, I need to be able to find additional information on why I need to change my Notify password so that I can brief up, relieve any concerns and answer my questions without having to reach out to Notify Support. 
As a (user), I need to know about the security issue that caused a password reset so that I can have confidence in Notify and avoid contacting support with questions 

WHY are we building?
We had a security issue that caused us to have to force a password reset for all users 

WHAT are we building?
Content for an update on a new System Status page

VALUE created by our solution
More confidence, more transparency and fewer support tickets (self-serve, less human intervantion)

## Documentation and Artifacts

Incident info in Slack thread: https://gcdigital.slack.com/archives/CAG3WKMC4/p1674586969797649?thread_ts=1674586958.406919&cid=CAG3WKMC4

Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Users are aware there was a security issue and that as a result we have asked all users to create a new password
- [x] Content is drafted along with FR content
- [x] Content is review by Policy Advisor @mtoutloff 
- [x] Review by @jimleroyer 
- [x] Review by Security/SRE folks (Pat/Calvin)
- [x] Content is approved by PM
- [x] Growth team is advised and given an opportunity to review before finalized
- [x] Content is translated 
- [x] Content is drafted in GC Articles 
- [x] Translation

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [x] Tested in a realistic production scenario

**Comment by amazingphilippe** [comment]
Meeting with Jimmy and Ramya

Context:
Reiterated that we don't want to send an email to everyone
Design team still wonders what details to give when people stumble on password reset


Notes:
Possible question: if there were no breach, why do I (user) need to do a password reset?
Give reassurance that things are secure. Explain why we ask for a password reset

What happens if users try to skip the password reset. Shouldn't be a problem: They will be prompted at next login attempt. 

Multiple prompts to reset password. Can we have a metric to detect if some users get stuck in a reset loop?

Really good idea to link status page from the contact page for this user story.

Ramya and Jimmy team will draft a few canned responses. To be reviewed later.

**Comment by yaelberger-commits** [comment]
@YedidaZalik I think we can now move this task to done. Do you agree?

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1187?planning-poker) with Zenhub @YedidaZalik @mtoutloff

**Comment by YedidaZalik** [comment]
@yaelberger-commits yes - it's done!
