### ISSUE TITLE
Dashboard time period differs from notification reports time period

### ISSUE THREAD

**Issue by whabanks** [cds-snc/notification-planning#1193]
## Dashboard time period differs from notification reports time period
The dashboard currently uses a 24 hour time period for displaying message and problem address counts.
The notifications report page displays messages from a 1 week time period.

Slack thread: https://gcdigital.slack.com/archives/C04RU1B0YJ1/p1683040356877929

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major 

## To Reproduce

1. Go to the dashboard of a service with sends across several days
2. Click on 'Review Reports'
3. Note that the reports page displays messages from the last week

## Expected behavior
Both the Dashboard and Reports pages should be consistent in the timeframe of messages that they show, whether it is a week, 24H or some other time frame.
Sections on the dashboard should each have their own timeframe that is most useful for that data. Not all sections need to share the same timeframe.
The timeframe should be identified in the section heading. 

## Impact
A lack of clarity to the user when the number of messages they see on the dashboard differs from the number of messages seen in the report page. Confusion or difficulty accurately assessing their bounce rate for the last 24H when the reports page displays problem addresses from the last week.

If applicable

Impact on Notify users: Losing visibility into weekly data much sooner, from the dashboard. 

Impact on Recipients: None

Impact on Notify team: This might be a disruptive change. Existing clients might find that something is strange, and ask for technical support.

## Screenshots

From 0 to 1890. Not great for discoverability, less intriguing to click on a big 0. 
![image.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/179e5f88-d8a5-4d87-9290-976a030c160e)

## Additional context

There could be an option that allows us to keep both timeframes on the dashboard. if we find that it makes sense to create a completely new section for problem addresses, instead of adding it within the weekly stats section. See Figma mockups. 

## Supporting documentation

[Figma screens](https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?type=design&node-id=1017-12393&t=d8DrnLxMWcAcObWV-4)

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1193?planning-poker) with Zenhub @adriannelee @andrewleith @smcmurtry @whabanks @YedidaZalik

**Comment by yaelberger-commits** [comment]
Dev-design review needed to continue this work. 
@whabanks implemented some designs to start

**Comment by andrewleith** [comment]
- @amazingphilippe reviewed this Thursday based on feedback received
- Will continue work today in order to get towards hand-off

**Comment by YedidaZalik** [comment]
June 19/2023 content critique
- Charlotte: what are “problem email addresses” ? Wondering if there’s a more specific word other than problem “undelivered” “bounce backs”
- Anik: can we condense the squares - could “problem email addresses” fit under failures as part of progressive disclosure. That was previous iteration of dashboard, but they’re one type of failure among many, you’ll have less problem addresses than failures, also time frame differs
- First H2 is action and rest is info,  but action is less emphasized - because it’s for new users
- Anik; is it possible to have customized or tailored version where only see part of dashboard when it’s relevant?  We’ve been debating because maybe helpful to show empty states
- Anne-Sophie, email marketing software: Mailchimp delivered v undelivered, maybe need separation btwn first part and second part for “Account performance” or “Statistics”
- Alexa curious on start sending being above dashboard, why would they go there to start a message 
- Welcome or Get started screen
- Explanation for why you would see nothing maybe could go below instead of having primary thing on the page - If you’re not seeing anything here you probably haven’t sent any messages 
- We could do something more dynamic
- Anik: might the order be different for different stages? How many messages you have left might be most relevant? 
- 10 000 remaining v 100% 
- Alexa would think of the percentages as the opposite
- Anne-Sophie - can you calculate conversion rate? We know sometimes that emails are received but not all the time, its up to the service owners to manage their lists, some do have unsubscription links, could show how many bounced, how many were bad and how many were good

**Comment by andrewleith** [comment]
- @amazingphilippe working on figma designs for things we can action immediately; may show some during dev/design review

**Comment by amazingphilippe** [comment]
We'll have to split this story into 2 for now, to wait results from some upcoming research:


> Re: bounce rate, Yael and I are going to run an interview with a service that consistently has a high bounce rate. We’re going to frame the interview more generally around how they use their dashboard. We’ll ask them more specific questions about their bounce rate in the interview.
This will help us inform the research we’ll do on how people use the dashboard and we’ll get to hear a bit about the bounce rate design before we do a bigger round of research later in the summer. 
@Yedida she/her
 I think you’ll have more data about “problem email addresses” after this interview. I don’t think you have enough information to change it right now

https://gcdigital.slack.com/archives/G010A3CDV5X/p1687275707680199


---
Phil needs to properly document to states and combination, and we can go back to coding this in #notification-admin/1556

**Comment by amazingphilippe** [comment]
Commenting with some kind of AC for this bug story to capture the work done so far. Edit this if you'd like to add to it. 

- [ ] Design sections for the screen
- [ ] Better document status permutations in Figma
- [ ] Implement new section layout
- [ ] Create a story for new section title content, if needed
- [ ] QA big number component, make sure it still works in the admin panel
- [ ] Test big number component with voice over
- [ ] Test hover and focus states on the big number component

**Comment by adriannelee** [comment]
Will and Steve worked on creating manageable chunks. Will will continue working on this today.

**Comment by smcmurtry** [comment]
I've got a PR up for the layout change that is ready for review. After it is merged, it will be visible on Staging but not in Production until we set the v1.5 feature flag to `True` in production.

**Comment by smcmurtry** [comment]
I linked another PR to this that is ready for review: "update the logic for the bounce rate colour".

**Comment by smcmurtry** [comment]
The bounce rate colour PR is merged and ready for QA in staging.

**Comment by andrewleith** [comment]
I went to QA this but I see discrepancies in my dashboard (svc id `b9d1d40c-8029-48b9-b872-0c139812b7be):
![image](https://github.com/cds-snc/notification-planning/assets/823749/b37b5651-fc1a-4253-b519-69d208c9f9ad)
![image](https://github.com/cds-snc/notification-planning/assets/823749/ded98224-2dd7-4436-bc9e-125c28a4a842)

@smcmurtry was this not merged? 🤔

**Comment by smcmurtry** [comment]
Good catch @andrewleith ! I think we must have forgotten to update the time period from 24 hours to 1 week for the emails sent. I'll take a look.
