### ISSUE TITLE
Dashboard includes limit counter

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1306]
## Description
As a Sender, I need to be aware of daily limits for SMS and email so that I can plan and send messages without running into errors. 

WHY are we building?
- Without awareness of daily limits ahead of sending, Senders could be surprised to know there is a limit

WHAT are we building?
- **Dashboard** to indicate how many messages Senders have left for their service, for the day

VALUE created by our solution
- Increase confidence for Senders that they won't run into a last minute error
- Fewer surprises about daily limits
- Easier for Senders to help us meet our business need
- 

## Documentation
- [Figma](https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?type=design&node-id=2082-554&mode=design)
## Acceptance Criteria
- [x] (English) On the dashboard the Sender would likely understand their SMS and email daily limits
- [x] (French) On the dashboard the Sender would likely understand their SMS and email daily limits
- [x] The elements would be easy to access using assistive technology (Screen reader, alt navigation, magnification)
- [x] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [x] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- [Insight 2 and the linked findings](https://airtable.com/appWwAmHwDLtpIyko/tblqw9ekiSqDmMTHa/viwlUUKmOBaY5TWch/reckSDTjayP0iafOt?blocks=hide)
- [Doesn't know how to check SMS limit. Some messages didn't get sent / got lost due to going over the sending limit unknowingly](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwtsq6Gy7TDVGL36/recnHu2fPU09wWZbx?blocks=hide)
- [For both prototypes, the limits info was mostly unnoticed until after sending.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recKCbWxMlwXavAwq?blocks=hide)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1306?planning-poker) with Zenhub @adriannelee @amazingphilippe @YedidaZalik

**Comment by yaelberger-commits** [comment]
This sprint we will assess if designs are ready

**Comment by amazingphilippe** [comment]
Started designing the dashboard. Added Figma link to Story description

**Comment by amazingphilippe** [comment]
Interaction design is ready. Will work on content+interaction when Yedida is back

**Comment by YedidaZalik** [comment]
Yedida worked on this today and will review on Monday with fresh eyes, make any changes and seek feedback

**Comment by YedidaZalik** [comment]
We now have various possible iterations. Taking to content critique today.

**Comment by YedidaZalik** [comment]
Content critique

I explained: Counting up - showing “used/sent” rather than remaining to keep the pattern 
We do have an email in which we’ll give them numbers for  used/sent and for remaining

https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?type=design&node-id=2239-408&mode=design&t=uHpCgy1fQZcVXLLZ-0


Like the last one, stays within pattern with specifics of what a day is in the “Resets” is clean. Easy to scan

Curious what the behaviour would be - if rests at 7, goes to 0 - is that at all flexible - dissonance if use “today” ****
- Most people will be done working, but after 7 pm it’s still today, but it’s actually tomorrow is a weird conflict. Is it midnight in another time zone
- Resets at 7 pm seems to be related to emails only

Curious on having emails and text messages below the bar.


Get Email and Text messages higher because it’s one of the last things you read 

If there’s a different way to frame when it resets — in the last 24 hours

In the last 24 hours may not represent the same information - goes back to 10 am or 3 pm yesterday
May not be a problem for content to solve - request higher daily limit

- Could we focus on how much time left before reach limit ?

**Comment by amazingphilippe** [comment]
Created dev card #1334

**Comment by YedidaZalik** [comment]
Sent to translation today
https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-[…]type=design&node-id=2354-4573&mode=design&t=RoJ26o6tzZUG4U06-4

**Comment by YedidaZalik** [comment]
Nick has translated this and Marie-Sophie will take a look before finalizing.

**Comment by YedidaZalik** [comment]
Translation is back: https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?type=design&node-id=2548-101&mode=design&t=w5uisVoDuxNmEkaX-0

**Comment by amazingphilippe** [comment]
Translations are integrated in Figma and ready for dev.

**Comment by yaelberger-commits** [comment]
Adrianne will update Airtable with these fixes
