### ISSUE TITLE
Github security advisory re: host header injection

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1342]
## Github security advisory re: host header injection
As a GC Notify user, I need to know that there was a security vulnerability with GC Notify and that it was fixed and poses no risk, so that I can have confidence in the Notify product and team, and so that there is transparency and good communication between the Notify team and its clients.

WHY are we building?
We have a security vulnerability that we fixed and would like to be transparent about it 

WHAT are we building?
A security advisory in our github terraform repo, and link to the same content in System Status page too to keep a public record.

VALUE created by our solution
transparency and good communication with clients

## Documentation and Artifacts
[@jimleroyer's draft for content review](https://docs.google.com/document/d/1vZwVYcpU2z__Dim33i2OEpHQRCPk0XKomTWpDgsXvxY/edit)
[Figma for the system status page](https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?type=design&node-id=1412-914&mode=design&t=4jeYy07llvR6X2zT-0)

## Acceptance Criteria
Given a user reads our documentation in github, when they go to the ['Advisories' section](https://github.com/cds-snc/notification-terraform/security/advisories) of our terraform repo, they will be able to read a security advisory in EN or FR about the vulnerability and how we fixed it. 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps
- [x] Content is present in both English and French on the ['Advisories' section](https://github.com/cds-snc/notification-terraform/security/advisories) of our terraform repo
- [ ] Content is present on the system status page [link?]

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1342?planning-poker) with Zenhub @jimleroyer @YedidaZalik @yaelberger-commits

**Comment by adriannelee** [comment]
Edited the card to describe what the google doc is of and links to where the content will live. I also changed the 'WHAT' -> the content should link from one to the other to reduce duplication and in case the final content ends up too long for the system status page.

**Comment by adriannelee** [comment]
Jimmy and I decided that the security advisory itself should stay technical and detailed since it will likely only be viewed by a technical audience. The Github security advisories may also get queried and taken out of context. 

The Systems Status screen will be content for a more general audience and provide a summary of the issue and link to the security advisory. 

I edited Jimmy's draft a bit and worked on the System Status page. Up for review by Jimmy.

**Comment by adriannelee** [comment]
Worked with Anik, Phil, and Marie-Sophie on this today. Not yet ready for translation.

**Comment by adriannelee** [comment]
Decided that the security advisory going on Github can be published first. Since the update on the Notify System Status screen won't be linked from anywhere anyways. Sent the [security advisory to translation](https://trello.com/c/iQobzwVq/1613-notify-github-security-advisory-274-words-adrianneleecds-sncca).

The System Status update still needs some work.

**Comment by mtoutloff** [comment]
In final review with Jimmy R.
Can be published asynchronously with translation

**Comment by adriannelee** [comment]
Finalized the content for the System Status page update. @amazingphilippe helping out with getting the Figma file to translation.

The security advisory going on Github came back today. Will post on Github with @jimleroyer tomorrow.

**Comment by adriannelee** [comment]
The system status content was translated last week. I will work on getting it on GC Articles today.
