### ISSUE TITLE
DEV: Update Contact Us Page to direct users to new demo sign up page

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1485]
## Description
As a public servant interested in learning more about GC Notify, I need to be able to sign up for a demo, so that I can attend and see the product in action and get my questions answered.

WHY are we building?
Allow clients to self-serve and take some burden off the Support Team

WHAT are we building?
Removing the request a demo option from our Contact Us form and replacing it with content linking users to the Demo sign up page managed by Growth 

VALUE created by our solution
Users won't need to go through Support to request a demo, they will be able to self-serve and choose their session themselves.

## Acceptance Criteria
Given a user wants to attend a demo, when they go to our Contact Us page, then they can select a link to a demo sign up page and self-serve from there. 

- [x] Request a demo option is removed from the Contact Us form
- [x] Content that links to the new demo sign up page is added to the Contact Us page
- [x] When a users wants to sign up for a demo, the Support Team is not needed to intervene at all
- [x] The link sends you to EN from the EN Contact Us page
- [x] The link sends you to FR from the FR Contact Us page
- [x] New demo sign up page loads within 200 milliseconds (dependancy with Growth)
- [x] GA4 is used to track engagement with the link

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps
- [x] When a users wants to sign up for a demo, the Support Team is not needed to intervene at all
- [x] The link sends you to EN from the EN Contact Us page
- [x] The link sends you to FR from the FR Contact Us page
- [x] New demo sign up page loads within 200 milliseconds (dependancy with Growth)
- [x] When you click the new link to the demo sign up page it is logged in GA4

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1485?planning-poker) with Zenhub @adriannelee @amazingphilippe @YedidaZalik

**Comment by jzbahrai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1485?planning-poker) with Zenhub @jzbahrai

**Comment by YedidaZalik** [comment]
Forms invites people to contact them if they can't attend on the scheduled dates. This is also the way to request a French session (but Forms only does that on the French page, and the French page does not indicate that users can also request a different day/time; my draft is based on having the same info on both pages). On the Forms Contact us page, the only option that users can use to request a different date or French session is "Other". It would be a simpler flow to have the user go directly to a page specifically for that purpose so Yael and I asked if we could have something that links users directly to the Growth team instead. But Growth is not able to do that and it's out of scope for us to do it.
So we still need some kind of option to request a different date or French demo on Notify's contact us page. Users may land on the contact us page before they land on the request a demo page, so we'll have to specify on "Contact us" that they only request a demo date if they cannot attend the demo dates on the other page.
I've got a first draft done of both the demo page and the new contact us page in one document (because they have to work together). I've provided 2 options, the first option uses "Other" to request a French demo or alternate date. The second has a specific box on "Contact us" for a French demo/alternate date.
I've tried to highlight what's different in light purple to make it easier to see the difference. Asked designers to comment in notify-research-design channel
[Attend a demo page and new Contact us page](Forms invites people to contact them if they can't attend on the scheduled dates. This is also the way to request a French session (but Forms only does that on the French page, and the French page does not indicate that users can also request a different day/time; my draft is based on having the same info on both pages). On the Forms Contact us page, the only option that users can use to request a different date or French session is "Other". It would be a simpler flow to have the user go directly to a page specifically for that purpose so Yael and I asked if we could have something that links users directly to the Growth team instead. But Growth is not able to do that and it's out of scope for us to do it.
So we still need some kind of option to request a different date or French demo on Notify's contact us page. Users may land on the contact us page before they land on the request a demo page, so we'll have to specify on "Contact us" that they only request a demo date if they cannot attend the demo dates on the other page.
I've got a first draft done of both the demo page and the new contact us page in one document (because they have to work together). I've provided 2 options, the first option uses "Other" to request a French demo or alternate date. The second has a specific box on "Contact us" for a French demo/alternate date.
I've tried to highlight what's different in light purple to make it easier to see the difference. Asked designers to comment in notify-research-design channel
Attend a demo page and new Contact us page)

**Comment by YedidaZalik** [comment]
Keenan kindly offered to use his email as contact for French and alternate dates and this was approved by Bryan and Yael
Implemented that and rest of designer feedback in document
Marie-Sophie also reviewed for localization issues
Ready for dev design review

**Comment by amazingphilippe** [comment]
Figma for demo pages and sections: https://www.figma.com/file/f6QILuxf94EHaStf2ejWJb/Contact-us-%7C-Nous-joindre?type=design&node-id=1338-4945&mode=design

**Comment by amazingphilippe** [comment]
Sent to translation

**Comment by YedidaZalik** [comment]
Translation is back https://www.figma.com/file/f6QILuxf94EHaStf2ejWJb/Contact-us-%7C-Nous-joindre?type=design&node-id=1384-159&mode=design&t=JGfUy2IkLNuoWAFC-0

Do we need to annotate and show at dev design review?

**Comment by YedidaZalik** [comment]
Figma screen with both languages
https://www.figma.com/file/f6QILuxf94EHaStf2ejWJb/Contact-us-%7C-Nous-joindre?type=design&node-id=1405-3316&mode=design&t=NeFD3CI8fhMorSr8-0

**Comment by YedidaZalik** [comment]
Created GC articles pages (without images or demo dates yet)
Permalink for EN is register-for-a-demo and for FR is sinscrire-a-une-demo

**Comment by amazingphilippe** [comment]
@andrewleith has a PR. Still failing though
Also needs the GCA page to be live

**Comment by andrewleith** [comment]
This PR is ready to go, just waiting to [merge the updated WAF rules](https://github.com/cds-snc/notification-terraform/pull/1166) to make the pages accessible.
