### ISSUE TITLE
Dashboard not reporting bulk sends

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1605]
## Describe the bug 

The dashboard isn't reporting bulk sends, although they show up below under bulk sends.

First steps could be to replicate the problem and document the steps for reproduction

Related freshdesk ticket https://cds-snc.freshdesk.com/a/tickets/17971

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major

## To Reproduce

1. Go to a service that just sent a bulk send
2. Look at the dashboard and see a few thousand sends
3. Scroll down to bulk sends
4. See that nearly 80k emails have been sent.

## Expected behavior

The dashboard of messages sent this week should include all messages sent from the service, including bulk sends.

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: Confusion as to why their messages are not showing on their dashboard. This could lead users to resend messages if they think they never sent.

Impact on Recipients: Might receive duplicate message

Impact on Notify team: More support tickets, confusion for the support team

## Screenshots

https://cds-snc.attachments6.freshdesk.com/data/helpdesk/attachments/production/61050541502/original/jx1ieckjV727Ad4GCY2XdpnJDpn9LTThYg.png?Expires=1725996412&Signature=AdZ6gwhL136zn1azstTsncECX61O5JjjZqanTJZnJfgmmVJE5KYqBZxkGGypr8MRM21--N6c-qEoHuHdV8rZ1wRvBJstIfcCqeBQv1ai-Ez65UWcfpVdkzGu7mOeKsv66EoyJgmSlh8C0aiLOfJGyK446VYWNtYV0-LwKRtMjw~zThVyKXCaA3xP8WnkL~tKKAHI3dDYsK7adQLpJUehru1oo47eZcKbN~4Mu4Re5bRBaLVORpauuS5Y5uZ2v4J3K7ORnK2zBFyALNfE2gXvYOLkKkRm1KhieiMmqpkTtaeUrdtzIXaTyWaBftyWFQj9Fr0cdq2Py1MvQR5B8JHHNw__&Key-Pair-Id=APKAJ7JARUX3F6RQIXLA

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1605?planning-poker) with Zenhub @andrewleith

**Comment by andrewleith** [comment]
Some notes from investigation:
- We still have some discrepancies in the data inside of our fact table
- [The fact table is populated nightly](https://github.com/cds-snc/notification-api/blob/main/app/config.py#L447)  as aggregates at `05:30AM UTC`
- [When it runs](https://github.com/cds-snc/notification-api/blob/main/app/celery/reporting_tasks.py#L60), it chooses dates based on the time its running rather than a fixed time like midnight UTC, which could be a cause or partial cause of this issue
- The stats from the client's bulk sends were not yet in the fact table, so they didn't show up in certain parts of the dashboard, notably the weekly stats and the template stats.  However, the bulk stats section of the dashboard isn't based off of the fact table, so they showed up in that section.

Possible ways forward:
- Revise nightly stat creation and ensure they are based on a fixed time of UTC midnight, as this is the date we advise the users of in the UI
- Revise how stats are gathered and calculated across various parts of the dashboard and ensure queries are consistent and based off the same source

**Comment by yaelberger-commits** [comment]
It also shows no problem email addresses for the week, but I can see from the reports that there were many "email does not exist" statuses reported back, so there should have been problem emails.

**Comment by amazingphilippe** [comment]
Nightly reporting task is querying at the wrong time: missing a chunk of notifications until the morning. The entire dashboard uses a slightly different refresh timings. Go through story refinement and break the problem in smaller pieces.

**Comment by yaelberger-commits** [comment]
Part of a bigger EPIC that we will scope during Story Refinement

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1605?planning-poker) with Zenhub @jzbahrai @whabanks

**Comment by yaelberger-commits** [comment]
Yael to find freshdesk ticket related and a screenshot

**Comment by andrewleith** [comment]
This has been fixed by the general work in fixing the dashboard.  Since the facts job now correctly puts all data from the day into the table (instead of starting at 4am) we dont have missing data at different times of day.  🎉
