### ISSUE TITLE
As a user, I want to clear the cache after a deploy

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1612]
## Description
Once we do a deploy, I want to clear the cache of Templates, TemplateCategories, Services, User, EmailBranding, Organisation

## Acceptance Criteria
- [x] Check that the above entities that are in the cache pre deploy, are removed post deploy

## QA Steps
- [x] Tested in staging

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1612?planning-poker) with Zenhub @jzbahrai

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1612?planning-poker) with Zenhub @andrewleith @whabanks

**Comment by yaelberger-commits** [comment]
@andrewleith is working on this one today

**Comment by andrewleith** [comment]
TODO: 
- [ ] Misc: generate new CACHE_CLEAR_CLIENT_SECRET 
- [ ] Add CACHECLEAR_SECRET_KEY to github secrets
- [ ] MANIFESTS - Add CACHE_CLEAR_CLIENT_SECRET to .env so that API can use it to authenticate calls to the new endpoint
- [ ] UTILS - Move the list of cache keys here so they can be used by both admin and API
- [ ] API - Add a new protected endpoint that will clear all redis caches from the list in utils
- [ ] TF - Update the WAF rules to allow the new api endpoint to be called
- [ ] ADMIN - (Optional, can come later) Update the admin cache clearing logic to use the list from utils, instead of the list currently hardcoded in admin
- [ ] MANIFESTS - Update one of the deployment workflows to call the cache clearing endpoint after deploy using new secret key

**Comment by yaelberger-commits** [comment]
2 PRs up, Jumana may pick this up today or when Callback work is done

**Comment by yaelberger-commits** [comment]
Mostly done, working in Staging. Next step is to merge in Staging

**Comment by yaelberger-commits** [comment]
Got it working in Staging, but failed in Prod. Jumana will take a look today.

**Comment by jzbahrai** [comment]
this is done! https://github.com/cds-snc/notification-manifests/actions/runs/10814319807/job/30000671945
