### ISSUE TITLE
Clarify timezone in the UI when scheduling

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1630]
## Description
As a Sender scheduling a bulk send, I need to be able to know if the time zone is EST, UTC or something else so that I can control when the messages will arrive in recipients' inboxes. 

WHY are we building?
https://cds-snc.freshdesk.com/a/tickets/18502
https://cds-snc.freshdesk.com/a/tickets/18789

Feedback from a client
We don't have the timezone in the scheduler

WHAT are we building?

1. Add content to clarify timezone when scheduling a bulk send
2. In guidance, reassure that time strings are local
3. Add content at sign-in history to clarify timezone is local

VALUE created by our solution
Better UX, less friction. A reference for future support requests, and for the team. 

## Documentation and Artifacts

Document
Figma?

## Acceptance Criteria
Given a sender is scheduling a bulk send, when they go to schedule their send, then see the time zone the product uses and can figure out what time to schedule so that messages arrive in recipient inboxes when expected. 

- [ ] Add content to clarify timezone when scheduling a bulk send
- [ ] In guidance, reassure that time strings are local
- [ ] Add content at sign-in history to clarify timezone is local
- [ ] Cypress UI tests if needed.

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1630?planning-poker) with Zenhub @YedidaZalik @amazingphilippe

**Comment by yaelberger-commits** [comment]
our testing confirmed that the scheduler is in the sender's local time, based on their IP address

**Comment by amazingphilippe** [comment]
Pages we can consider updating:

Specify "local time" on these occurences:
- Scheduler: specify "local time" in confirmation box or instructions. (Most important)
- Job: specify "local time" in the table row (Important)
- Dashboard - might be redundant
- Jobs (plural) - might be redundant
- Any other local time strings? Any local strings not in a long list?

Add a guidance section to make it clear that all times are local, unless marked otherwise.

<img width="833" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXBVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad5f50084e0436191a7bcaa8e7235790df3daa83/Capture%20d%E2%80%99e%CC%81cran%2C%20le%202024-08-13%20a%CC%80%2013.15.17.png" alt="Capture d’écran, le 2024-08-13 à 13.15.17.png" />
<img width="998" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTVVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc855b667fa8f4e58ee78d0c9a866a25be5796b4/Capture%20d%E2%80%99e%CC%81cran%2C%20le%202024-08-13%20a%CC%80%2013.15.32.png" alt="Capture d’écran, le 2024-08-13 à 13.15.32.png" /><img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkpVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e36e621de94ed3ddbb308d4237b30d4f22d0a5db/Capture%20d%E2%80%99e%CC%81cran%2C%20le%202024-08-13%20a%CC%80%2013.15.40.png" alt="Capture d’écran, le 2024-08-13 à 13.15.40.png" />

**Comment by amazingphilippe** [comment]
Can we convert the daily limit reset time string to local time? Not here, but good to consider later. 
Can we indicate timezone in column headers. Sure, for a future iteration

**Comment by YedidaZalik** [comment]
Started on content here: https://www.figma.com/design/fRVRKm7cM8MUuBWUJbrfgU/Sending-from-web-interface-%7C-Envoyer-par-interface-web?node-id=6678-16627&node-type=FRAME&t=P9vWKfPN2EEPaTao-0

Realized that several instances of "local time" could be viewed by team members in different time zones. How will we clarify whose local time we're referring to?
Need to resolve this before tweaking Guidance content

**Comment by YedidaZalik** [comment]
Sync with Phil and Yael - clarified that each team member sees their local time based on their IP address.
Eg.  a team member in Ottawa schedules the send in EST. Another team member in Vancouver accesses the screen that gives the scheduled time. The Vancouver team member's screen will give the time in PST.

**Comment by yaelberger-commits** [comment]
Yael & Phil reviewed with Yedida at our weekly sync this morning. Bringing to Dev/Design Review today to share with the devs for implementation handoff

**Comment by yaelberger-commits** [comment]
Yael & Phil reviewed with Yedida at our weekly sync this morning. Bringing to Dev/Design Review today to share with the devs for implementation handoff

**Comment by YedidaZalik** [comment]
Discussed during dev-design review, decided:
- can omit reference to IP address
- reference to local timezone needs to appear earlier on the scheduler page. Yedida to work on wording.

Yedida looked back at the support requests and both have the word "use":
". . . which timezone is used?"
" . . . guess that this application is using Eastern Time..."
So changed to "The calendar and clock use your local timezone".  Did not go with "Use your local time zone" as that could be interpreted to mean that the person must figure out what their time zone is and then use that time zone to schedule their send.

Designs for the [2 screens we decided to revise in figma](Before you continue
Your account
Français
GC Notify always shows your local time, except where we state otherwise. 
GC Notify
Service name
Switch services
Start
About the portal
Templates
Manage team
API integration
Support
Team members
Settings
Dashboard
Review our records for your last 3 sign in times:
Back
Today, 1:36 PM
PC / Mac OS X / Firefox
Schedule email 
Today, 1:36 PM
PC / Mac OS X / Firefox
The calendar and clock use your local timezone.
Today, 1:36 PM
PC / Mac OS X / Firefox
If our records are not correct, contact us.
By using GC Notify, you agree to:

Accept conditions, including those in our Privacy notice
Accept sending limits
Accept risks when sending text messages
Manage and protect personal information of your recipients
Get consent before sending messages
Keep accurate contact information
Send information that's unclassified or Protected A only
Practice continuous security
Message scheduled for:
Agree and continue
Sign out
Thursday, January 9, 2020 at 9:00 AM local time     
You can cancel this send before the scheduled time.
Schedule
About
Support
Why GC Notify
Documentation
Features
Contact us
Activity dashboard
.
Privacy
Security
Terms of use)

**Comment by YedidaZalik** [comment]
Ready for localisation when MSB has time
The FR screens are prepped for her under the 2 EN screens
https://www.figma.com/design/fRVRKm7cM8MUuBWUJbrfgU/Sending-from-web-interface-%7C-Envoyer-par-interface-web?node-id=6716-1296&node-type=frame&t=UsLn0OAL2i9EGFmc-0

**Comment by amazingphilippe** [comment]
Openend a PR to address changes in the scheduler: https://github.com/cds-snc/notification-admin/pull/1949

**Comment by andrewleith** [comment]
Review is complete - should be good to be merged once translations are in.

**Comment by YedidaZalik** [comment]
Looks like these may have been translated - will check with MSB
https://www.figma.com/design/fRVRKm7cM8MUuBWUJbrfgU/Sending-from-web-interface-%7C-Envoyer-par-interface-web?node-id=6676-365&node-type=canvas&t=2ue0OXI2vrtJZ52A-0

**Comment by amazingphilippe** [comment]
Translations added to the PR. Ready to merge once automated checks are passing

**Comment by amazingphilippe** [comment]
Merged. More content to tweak on the login history screen
