### ISSUE TITLE
Performance test against new canary system

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#235]
**Description**

As a Notify Developer, I want to test the performance of the new canary system, so we can deliver a new metric with a 50/50 integration. 

**WHY are we building this?**

We are building this to be able to see the performance of the notify app.

WHAT are we building?

VALUE created by our solution

**Acceptance Criteria**

- [x] - Successfully performance test the notify application.
- [x] - Make sure traffic is split 50/50 with the new integration to test the canary system that the traffic split is working as expected (look at performance test from night before)

**Comment by sastels** [comment]
Should increase the users / minute and see if there's an improvement in the 50/50 case.

**Comment by yaelberger-commits** [comment]
Fine tune the test a bit more so we can deliver a new metric

**Comment by yaelberger-commits** [comment]
Results in ADR

**Comment by sastels** [comment]
Ok, so the split in staging right now is actually 75% lambda, 25% k8s. So we would expect the daily performance test to use the lambda api 3 times as often as the k8s api. 

For the past week we graph the # hits per day to the api gateway in front of the lambda and the # hits to the api in the k8s cluster.
![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/3d2c4eca-6aa6-4999-9dbd-eb486a09ff66)

Note that the scale for the lambda line (left y axis) is 3x the scale of the k8s line (right y axis). Since the lines are pretty close together we see that the api lambda has been called about 3 times as often as the k8s api, as we had expected.

**Comment by jimleroyer** [comment]
Moving this to done this was meant to test staging with a 50/50 traffic split and we did it numerous time with reported results (in the ADR among others).
