### ISSUE TITLE
Integrate Mixpanel within Notify Admin back-end

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#295]
# Description

As a researcher,
I want Mixpanel integrated within Notify Admin back-end,
So that I can test an event for data analysis on user's behavior before expanding implementation for more events.

## WHY are we building?

We want to see a proof of concept for using Mixpanel so that eventually we can know how users use Notify Admin GUI.

## WHAT are we building?

We are plugging in Mixpanel solution to track certain tailored events within the Notify Admin **back-end**. We **don't want to integrate it with the front-end** because the Javascript code tends to be blocked anyway.

## VALUE created by our solution

Setting up tool to better serve our user experience.

# Acceptance Criteria

Given that we have Mixpanel integrated and 1 event sent, when the event is triggered, then the event is recorded within the Mixpanel dashboard. 

- [x] Mixpanel API key and URL are kept as secrets within the `.env` encrypted files for both staging and production environments within the notification-manifests repository.
- [x] Mixpanel is initialized within the Notify admin back-end, but only if the environment variable URL was defined in the environment.
- [x] Mixpanel can send 1 event from the Notify admin and display that event in its dashboard.
- [x] There are unit tests to make sure that the Mixpanel is called where it should be called.
- [x] Suggestion: Mixpanel related events sending should be in its own module so we can easily manage these. For example, a login event might be triggered from the login code but would refer to a `mixpanel.py` module where potentially a `send_login` event would be reported.

**Comment by sboots** [comment]
[Past documentation notes here](https://docs.google.com/document/d/1GSb1WOP0EtaGXYuoKdjUT5-ZC0kUDceixBJLetjbdNU/edit?pli=1#).

As a first step, I think tracking a "login" event would make sense. This can also include a user-profile call to Mixpanel along with the event itself.

We'd likely want an implementation where we have separate Mixpanel projects (and separate API tokens) for staging+testing vs. production. Happy to help set that up.

**Comment by jimleroyer** [comment]
Can we defer user profile as a requirement to another iteration? I feel this might be more sensitive and we are not sure yet what to send to Mixpanel, if I understand correctly.

**Comment by sboots** [comment]
@iokpala and I just touched base this morning – few quick updates here.
- Doing user profiles as part of this first step will be useful, so that we can test and learn how events are linked by the user profiles. If we defer it I think we'd lose a lot of the value of Mixpanel (vs. other tools like Google Analytics).
- As far as implementation, a module for Mixpanel sounds awesome. I think there'd be 4 basic parts that come to mind:
  1. Any initiation things that might be needed for the Mixpanel library (e.g. checking if the environment variable is set, if it is, go for it; if it isn't, don't run Mixpanel functions, so it's easy to "turn Mixpanel off" by removing the API token environment variable).
  2. An "update user profile" function, that calls the Mixpanel [user profile update](https://developer.mixpanel.com/docs/python#storing-user-profiles).
  3. A "send event" function, that sends a Mixpanel event (with a user ID matching the user profile update, e.g. the person's email address).
  4. A "get Mixpanel user ID" function, where the input is a Notify user's email address, and the output is *either* that same email address (if it's a Government of Canada employee), or, a consistently hashed version of it (if it's an email address that *isn't* a Government of Canada employee). For now it could just check if the email address ends in `.gc.ca` or `@canada.ca`
- When we send Mixpanel events, we'll want to send a `product: notify` variable so that, in the future, we can differentiate Mixpanel events from each CDS platform product (e.g. Notify vs. Forms vs. any future products).
- We'll have two separate Mixpanel projects, with different API tokens: one for staging/testing, and one for production use. Right now only the staging/testing Mixpanel project exists. Once we're ready to deploy this on Notify's production instance, we'll create a Mixpanel project for that. We'll keep the staging/testing Mixpanel project going so that we can use it to test future new event types etc.

**Comment by yaelberger-commits** [comment]
https://notification-feature-in-7gawzd.herokuapp.com/
