### ISSUE TITLE
Investigate stuck messages

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#695]
## Describe the bug 

Not all notifications get to a final state.

```
select notification_status as status, count(*), max(now() - created_at) as oldest
from notifications
where notification_status not in ('delivered', 'permanent-failure', 'technical-failure')
    and created_at < now() - interval '12 hours'
group by notification_status
```

| status  | count  | oldest  |
|---|---|---|
| sending  | 81  | 3 days 1 hr |
| temporary-failure  | 4017  | 7 days 9 hours  |

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
(SEV-1, SEV2, SEV3, SEV-4) 
SEV3 - some messages are getting stuck in limbo.  Isn't tied to one service.

## To Reproduce

No idea

## Expected behavior

All messages are eventually marked as 'delivered', 'permanent-failure', or 'technical-failure'.

## Impact

Some messages are stuck for no apparent reason. End users might not be getting the messages, and service owners do not know if their messages were sent or not.

**Comment by yaelberger-commits** [comment]
This could even be a SEV-2. I see the # of messages stuck is very low, but the fact that it is happening at all and we're not sure why is an issue

**Comment by jimleroyer** [comment]
[Just wrote an AWS ticket](https://us-east-1.console.aws.amazon.com/support/home?region=us-east-1&skipRegion=true#/case/?displayId=10220689141&language=en) to ask about this.

But also, I did some preliminary research. There are many notifications that are not updated due to our own (presumably) faulty logic. We could fix some of the status by fixing the following issues. There might be more as well, this is not an exhaustive search.

## No update of status on received complaint

Notifications that are in the suppression list [will not get their status updated but stuck at sending](https://github.com/cds-snc/notification-api/blob/bebd806cad9581101e5cc1d52db2613c1baa1fa9/app/celery/process_ses_receipts_tasks.py#L37). We can't say it should be sent but nor are we still sending it. 

```
"complaintSubType\": \"OnAccountSuppressionList\", \"feedbackId\": \"010d018153144072-7cd19a78-5d64-4bf0-be89-bff19022d8b4-000000\
```

We might need to update the code that receives the response callback to update the status. It seems that there is logic that exist to take a complaint in (i.e. due to suppression list in this case) and [tag it as delivered](https://github.com/cds-snc/notification-api/blob/bebd806cad9581101e5cc1d52db2613c1baa1fa9/app/notifications/notifications_ses_callback.py#L66-L70).

## Missing reference on status update

Some notifications can't be found in the database by reference, despite the fact that these very well exist with proper reference, for example: `notification not found for reference: 70ea849e-1ad6-4329-a3e7-3d798b28669f (update to delivered)`. That reference though exist in the database. It might be similar to another bug we have sometimes when we save a notification in the database and we're about to send it, but the sending process is too quick for the database to replicate the data among readers.

**Comment by jimleroyer** [comment]
Created two new cards deriving from previous quick investigation:
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/716
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/718

**Comment by yaelberger-commits** [comment]
Closing and carrying two other cards #716 and #718 forward
