### ISSUE TITLE
Investigate Bulk SMS blocking priority SMS

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#731]
_Investigate Bulk SMS blocking priority SMS_

**Description**

There seems to be an issue when sending bulk SMS where messages in the priority SMS lane are being delayed or blocked by the bulk messages. This shouldn't be happening. 

Miro board: https://miro.com/app/board/uXjVO3K9r9E=/

**Expected Behaviour**

**Acceptance Criteria**

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/731?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels @patheard

**Comment by yaelberger-commits** [comment]
Giving a higher weighting to priority SMS redis lane so we process these SMS faster could resolve this problem, but needs more discussion with the team

**Comment by sastels** [comment]
So I've done [some tests](https://docs.google.com/document/d/19e6WX8rHMnwLQliMYc8aVuSUdW8eAAPpIKwTqSdszBk) on staging, and priority SMS do not seem to be blocked by floods of bulk or normal. 

They are slowed down, but as we'd expect 
- Essentially we have three queues all going into the same celery workers.
- So if there are bulk and normal SMS to send, the priority ones get sent about a third of the time.
- However, it doesn't make a difference how many bulk and normal ones are in the system, a new priority one will go in to the front of the priority queue and quickly get sent off.

**Comment by yaelberger-commits** [comment]
@sastels added a special new number to Notify, not a test number right up until about to send to AWS. The doesn't send. Allows us to test all of our system

**Comment by yaelberger-commits** [comment]
Use Blazer graphs to monitor rates in production

**Comment by yaelberger-commits** [comment]
Could add the ability to add more celery tasks or ability to have celery not rate limit themselves so much

**Comment by yaelberger-commits** [comment]
Steve A and Jimmy will set up a meeting to review

**Comment by yaelberger-commits** [comment]
Jimmy and Steve will meet today

**Comment by jimleroyer** [comment]
Steve showed me his report:
https://docs.google.com/document/d/19e6WX8rHMnwLQliMYc8aVuSUdW8eAAPpIKwTqSdszBk

This is great data to investigate and use as a reference! This behaves as what we'd expect and answers our question on how our system behaves with SMS.

A potential culprit for the slow down experienced when this issue was opened is maybe some templates were sending many notifications and were set to high priority. I've moved some of these since then and hopefully templates in high priority should be as fast as being sent under a minute from now on. 

We can re-run the queries we used in the baseline to verify high median on any given day for SMS high priority, to make sure we don't have slow downs on the high priority lane.
