### ISSUE TITLE
Write email content to notify users we have updated our Terms of Use

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#775]
_Write email content to notify users we have updated our Terms of Use_

## Description

As a current Notify user, I need to receive notification that the Terms of Use have been updated so that I can know what contract I'm agreeing to by continuing to use Notify. 

As the Notify team, I need to notify current users that our Terms of Use and other policy documentation have been updated so that I can ensure users have the information they need to know what policies and contracts they're agreeing to by continuing to use Notify. 

WHY are we building?
We are updating our Terms of Use and need a user friendly way to notify current users of the changes so they are still aware of what terms they are agreeing to by using Notify

WHAT are we building?
An email with content to all current users

VALUE created by our solution
We don't have to create a UI solution to get current users to agree to the new Terms of Use
Current users can continue using our product without any disruption while also being aware of the changes to the Terms of Use. 
It may increase the likelihood current users will read the new Terms of Use if they receive an email about them. 

##Document**
[Email about updated TOU](https://docs.google.com/document/d/13fcrGcGHmD20paIaK4Zb8a1P-sst6GMf2irAKhyaMlI/edit) Note that requested Linguistic Svcs translate directly into this document as the EN and FR will go out in the same email

## Acceptance Criteria** (Definition of done) 

Highlight what's new, link to longer docs

- [x] Links to all 4 of the updated policy documents (Terms of Use, Service Level Agreement, Privacy Statement, Security Statement)
- [x] Highlight daily and annual limits for email and SMS
- [x] Protect your API key
- [x] 7 day data retention by default, 3-day available upon request for sensitive services
- [x] Maintain healthy email distribution lists and remove problematic emails 
- [x] Continuing to use GC Notify means you agree to the updated Terms of Use and accept your responsibilities as a client of GC Notify
- [x] Short, sweet and clear so that we maximize how many people will read it and how far down they read
- [x] Only link to policy documents, not link to anything else (ie. guidance)
- [x] Set up a new UTM link so when they click on policy documents we know how many click
- [x] Let support team know we will be sending out an email about changes to the ToU so they are prepared with any FAQs incase they get additional questions

## QA Steps

- [x] Tested in a realistic production scenario

**Comment by YedidaZalik** [comment]
Also include in the update email:
- for security reasons and to protect privacy, all file content is now deleted after 7 days, whether sent as a link or an attachment.

**Comment by yaelberger-commits** [comment]
Another example from Fitbit, this one about updates to a Privacy Policy 
![Screenshot 2023-04-14 at 9.42.31 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/6c962d7d-5210-4d5d-b96e-d5b13bc9a1d0)

**Comment by YedidaZalik** [comment]
**Content critique April 17, 2023**
- From line will be GC Notify so can cut that from Subject line
- Changes to our terms of use - "update" is over-used, may not draw people in as much as "changes"
- Reads as your new responsibilities include only these so need to rephrase
- Expecting something that shows the difference more, if user is not well read on tou, does not see the changes
- Not meant a TLDR - if TOU is fairly short and we want them to read it then should we give more of it to them. 
- Lots of links, is there a priority or hierarchy, assuming TOU is higher priority so is there a way to outline or layout text to emphasize TOU - list of the others
- Entice them to go to TOU - rather than synthesize responsibilities, could see there have been changes to your responsibilities and the terms of use to get them to click in: bite, snack, meal 
- Could we build the relationship, thank them for being a user, you could include all of it, more likely to read the TOU if add all of it to the email at the bottom, right now I’d feel like I’m in trouble because of the tone
- Adding something by continuing to use, please continue to read on for what you need to know
- Architecture of info is good, tone can be changed without adding "please"
- As a user, I have responsibilities, do I need to complete something, is it an ongoing responsibility 
- What do I need to do v what do I need to remind myself of for usage, try to achieve positive light tone with simple words
- Conditions of use thinks of what I have to do — something in present tense, more than “sending”

**Comment by YedidaZalik** [comment]
Met with @yaelberger-commits 
Went through comments from critique:
* From line will be GC Notify so can cut that from Subject line - yes
* Changes to our terms of use - "update" is over-used, may not draw people in as much as "changes" - yes 
* Reads as your new responsibilities include only these so need to rephrase - yes clarify
* Expecting something that shows the difference more, if user is not well read on tou, does not see the changes - No
* Not meant a TLDR - if TOU is fairly short and we want them to read it then should we give more of it to them - consider whether to put whole TOU in there, 2 versions, 1 with and 1 without
* Lots of links, is there a priority or hierarchy, assuming TOU is higher priority so is there a way to outline or layout text to emphasize TOU - list of the others - Depends on which version, we never told people we updated those and this would be a good opportunity to tell them what else has changed, Microsoft links at each at bottom if not full text - we have recently updated  - you should familiarize yourself with our other policy docs as well, here they are - all together outline your responsibilities and ours and we shortened them - do this in second version without whole TOU
* Entice them to go to TOU - rather than synthesize responsibilities, could see there have been changes to your responsibilities and the terms of use to get them to click in: bite, snack, meal - 
* Could we build the relationship, thank them for being a user, you could include all of it, more likely to read the TOU if add all of it to the email at the bottom, right now I’d feel like I’m in trouble because of the tone - don't use "thank you"
* Adding something by continuing to use, continue to read on for what you need to know - but not everything you need to know is in this email
* Architecture of info is good, tone can be changed without adding "please"
* As a user, I have responsibilities, do I need to complete something, is it an ongoing responsibility  - you accept by default so make sure you’re comfortable with them
* What do I need to do v what do I need to remind myself of for usage, try to achieve positive light tone with simple words but without 'please'
* Conditions of use thinks of what I have to do — something in present tense, more than “sending”

By continuing to use GC Notify, you have accepted our new terms of use. 

Yael’s suggestions:
- Understand your retention limits and conditions in our updated privacy notice
- Show default limits explicitly- don’t mention suspension, mention can ask for increase
- Instead of “accept” use “agree” to follow  for friendlier tone

**Comment by YedidaZalik** [comment]
Yedida working on 2 versions after meeting with Yael

**Comment by YedidaZalik** [comment]
Yedida has done 2 versions and putting into email format and then show to Yael.

**Comment by YedidaZalik** [comment]
Content critique

Content critique

Move link to full tou more visible —— have at top - first line TOU in first line

Abrupt - repeat part of subject line 
To ensure you agree — what are we ask us to do mandatory or recommended - 

New terms of use - 

After hello — 
 Here are the highlights - all on one line — all on 1 level - paragraph level - order — bold instead of headings
Nail structure before bolding
We have overhauled revamped these terms of use 

Setting the expectation that a lot of info has changed by bringing up terms under first heading  —  Bring all the links up. - then here’s the summary simplified

2 versions - announce releasing terms of use 2023

**Comment by YedidaZalik** [comment]
Yael to check 2 more versions that Yedida prepared

**Comment by yaelberger-commits** [comment]
Moved to blocked while we wait for translation

**Comment by amazingphilippe** [comment]
Translation is back. Phil, Yedida and Yael reviewed. 

We updated
- Email object in FR
- Added "if you have an API key"

We did not clarify that the changes apply to new services, we think it'll be fine.

**Comment by yaelberger-commits** [comment]
Yedida is drafting the message in GC Notify template for Yael to review. Yael has created UTM links for EN and FR to be added into the email body to get metrics on how many people click through to each version of the ToU from the email.

**Comment by yaelberger-commits** [comment]
Sending email 8am ET tomorrow morning

**Comment by YedidaZalik** [comment]
We sent to all Notify users on May 9.
On May 10, we used the reports of failed messages to extract the list of emails that failed due to "Inbox not accepting messages". 
On May 11, around 8:15 am, I resent the email to the extracted list of 64 recipients. Some are still sending at this time, 14 are in transit, 7 delivered and 43 failed.
